### ISSUE TITLE
Create the Engagement Wordpress Profile Page

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/Our-Project-Docs#36] opened 2015-09-22 22:45 UTC
As a program owner I need to create a profile page for Engagement WordPress instance so that I can collaborate with other innovators to improve the services this engagement site provides.

Created by: David Hume

DOD:
1. Ensure provenance  
2. Create draft content for all profile page sections
3. Be ready to send for final review and decision

Approach:

Connect with:
David Hume, Justin Hewitt, David Wrate, Todd Wilson.

**Comment by paulroberts68** [comment] 2015-10-07 17:25
Conducting some background work to confirm the application provenance. I've ascertained that only one contractor (from CGI) has produced code fort he core WordPress application.

**Comment by DavidR8** [comment] 2015-10-13 16:49
A security review of the code is also required prior to release.

**Comment by lmullane** [comment] 2015-10-21 18:01
@dy2288 Can you please create a profile page for the Citizen Engagement with full features. Once complete please reassign to @DavidR8.

**Comment by dy2288** [comment] 2015-10-21 18:57
Done: programs/Citizen%20Engagement%20Web%20Toolkit.

**Comment by lmullane** [comment] 2015-10-28 04:51
@dy2288 Can you please link to this repo: https://github.com/bcgov/citizen-engagement-web-toolkit Thanks!

**Comment by lmullane** [comment] 2015-10-28 05:38
@dy2288 Could you also please give @SteveMHoward edit powers to the profile page:) @DavidR8

**Comment by dy2288** [comment] 2015-10-29 00:17
I've added the Github URL and the editor to the list, however it seems like Steve isn't able to edit any content. @f-w, anything I'm doing wrong as far as you can see? Or is this a bug?

**Comment by f-w** [comment] 2015-10-29 18:04
@dy2288, you need to create an "editors" property of array type to the profile object. Add Steve's acct id to editors.

**Comment by dy2288** [comment] 2015-10-29 19:53
Access granted (not a bug). MongoVUE was reporting that the record for "editors" was overwritten, but actually just deleted it...

**Comment by pcrossley** [comment] 2015-11-03 19:29
waiting on feedback to then finalize

**Comment by DavidR8** [comment] 2015-11-04 23:10
Need to decide if pics are required for profile page

**Comment by lmullane** [comment] 2015-11-25 17:51
@f-w Please hide the Work With Us section on this page. @DavidR8
https://bcdevexchange.org/programs/Citizen%20Engagement%20Web%20Toolkit

**Comment by f-w** [comment] 2015-11-25 21:16
@lmullane, work with us is hidden. Back to you.

**Closed as completed** 2015-11-26 06:10 UTC
Labels: Profile Page, Bulls Eye Center, Account
